<?xml version="1.0"?>
<package format="3">
  <name>small_rover_description</name>
  <version>0.1.0</version>
  <description>Gazebo models and meshes for small_rover.</description>
  <maintainer email="devnull@example.invalid">sverk</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
